'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace OpenMedia
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IOpenMediaService", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class OpenMediaService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AddRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetOpenMediaRequestStatusByIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetOpenMediaRequestHistoryByIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetOpenMediaRequestsByTimeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAllOpenMediaRequestStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetServiceGroupStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAllOpenMediaServiceGroupStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetOptionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetOMAgentsByGroupOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DivertRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ModifyRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.OMInterfaceSM.My.MySettings.Default.OMInterfaceSM_OpenMedia_OpenMediaService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AddRequestCompleted As AddRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event CancelRequestCompleted As CancelRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event GetOpenMediaRequestStatusByIDCompleted As GetOpenMediaRequestStatusByIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetOpenMediaRequestHistoryByIDCompleted As GetOpenMediaRequestHistoryByIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetOpenMediaRequestsByTimeCompleted As GetOpenMediaRequestsByTimeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAllOpenMediaRequestStatusCompleted As GetAllOpenMediaRequestStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event GetServiceGroupStatusCompleted As GetServiceGroupStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAllOpenMediaServiceGroupStatusCompleted As GetAllOpenMediaServiceGroupStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event SetOptionsCompleted As SetOptionsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetOMAgentsByGroupCompleted As GetOMAgentsByGroupCompletedEventHandler
        
        '''<remarks/>
        Public Event DivertRequestCompleted As DivertRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event ModifyRequestCompleted As ModifyRequestCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/AddRequest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddRequest(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As AddOpenMediaRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> AddOpenMediaResponse
            Dim results() As Object = Me.Invoke("AddRequest", New Object() {request})
            Return CType(results(0),AddOpenMediaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddRequestAsync(ByVal request As AddOpenMediaRequest)
            Me.AddRequestAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddRequestAsync(ByVal request As AddOpenMediaRequest, ByVal userState As Object)
            If (Me.AddRequestOperationCompleted Is Nothing) Then
                Me.AddRequestOperationCompleted = AddressOf Me.OnAddRequestOperationCompleted
            End If
            Me.InvokeAsync("AddRequest", New Object() {request}, Me.AddRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddRequestCompleted(Me, New AddRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/CancelRequest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CancelRequest(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As CancelOpenMediaRequest, ByRef CancelRequestResult As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef CancelRequestResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("CancelRequest", New Object() {request})
            CancelRequestResult = CType(results(0),Boolean)
            CancelRequestResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelRequestAsync(ByVal request As CancelOpenMediaRequest)
            Me.CancelRequestAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelRequestAsync(ByVal request As CancelOpenMediaRequest, ByVal userState As Object)
            If (Me.CancelRequestOperationCompleted Is Nothing) Then
                Me.CancelRequestOperationCompleted = AddressOf Me.OnCancelRequestOperationCompleted
            End If
            Me.InvokeAsync("CancelRequest", New Object() {request}, Me.CancelRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelRequestCompleted(Me, New CancelRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/GetOpenMediaRequestStatusByID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOpenMediaRequestStatusByID(ByVal openMediaID As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal openMediaIDSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> GetOpenMediaResponse
            Dim results() As Object = Me.Invoke("GetOpenMediaRequestStatusByID", New Object() {openMediaID, openMediaIDSpecified})
            Return CType(results(0),GetOpenMediaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetOpenMediaRequestStatusByIDAsync(ByVal openMediaID As Integer, ByVal openMediaIDSpecified As Boolean)
            Me.GetOpenMediaRequestStatusByIDAsync(openMediaID, openMediaIDSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetOpenMediaRequestStatusByIDAsync(ByVal openMediaID As Integer, ByVal openMediaIDSpecified As Boolean, ByVal userState As Object)
            If (Me.GetOpenMediaRequestStatusByIDOperationCompleted Is Nothing) Then
                Me.GetOpenMediaRequestStatusByIDOperationCompleted = AddressOf Me.OnGetOpenMediaRequestStatusByIDOperationCompleted
            End If
            Me.InvokeAsync("GetOpenMediaRequestStatusByID", New Object() {openMediaID, openMediaIDSpecified}, Me.GetOpenMediaRequestStatusByIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetOpenMediaRequestStatusByIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetOpenMediaRequestStatusByIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetOpenMediaRequestStatusByIDCompleted(Me, New GetOpenMediaRequestStatusByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/GetOpenMediaRequestHistoryByID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOpenMediaRequestHistoryByID(ByVal openMediaID As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal openMediaIDSpecified As Boolean, ByVal retrieveLaterThan As Date, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal retrieveLaterThanSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> GetOpenMediaResponse
            Dim results() As Object = Me.Invoke("GetOpenMediaRequestHistoryByID", New Object() {openMediaID, openMediaIDSpecified, retrieveLaterThan, retrieveLaterThanSpecified})
            Return CType(results(0),GetOpenMediaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetOpenMediaRequestHistoryByIDAsync(ByVal openMediaID As Integer, ByVal openMediaIDSpecified As Boolean, ByVal retrieveLaterThan As Date, ByVal retrieveLaterThanSpecified As Boolean)
            Me.GetOpenMediaRequestHistoryByIDAsync(openMediaID, openMediaIDSpecified, retrieveLaterThan, retrieveLaterThanSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetOpenMediaRequestHistoryByIDAsync(ByVal openMediaID As Integer, ByVal openMediaIDSpecified As Boolean, ByVal retrieveLaterThan As Date, ByVal retrieveLaterThanSpecified As Boolean, ByVal userState As Object)
            If (Me.GetOpenMediaRequestHistoryByIDOperationCompleted Is Nothing) Then
                Me.GetOpenMediaRequestHistoryByIDOperationCompleted = AddressOf Me.OnGetOpenMediaRequestHistoryByIDOperationCompleted
            End If
            Me.InvokeAsync("GetOpenMediaRequestHistoryByID", New Object() {openMediaID, openMediaIDSpecified, retrieveLaterThan, retrieveLaterThanSpecified}, Me.GetOpenMediaRequestHistoryByIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetOpenMediaRequestHistoryByIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetOpenMediaRequestHistoryByIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetOpenMediaRequestHistoryByIDCompleted(Me, New GetOpenMediaRequestHistoryByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/GetOpenMediaRequestsByTime", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOpenMediaRequestsByTime(ByVal retrieveLaterThan As Date, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal retrieveLaterThanSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> GetOpenMediaResponse
            Dim results() As Object = Me.Invoke("GetOpenMediaRequestsByTime", New Object() {retrieveLaterThan, retrieveLaterThanSpecified})
            Return CType(results(0),GetOpenMediaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetOpenMediaRequestsByTimeAsync(ByVal retrieveLaterThan As Date, ByVal retrieveLaterThanSpecified As Boolean)
            Me.GetOpenMediaRequestsByTimeAsync(retrieveLaterThan, retrieveLaterThanSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetOpenMediaRequestsByTimeAsync(ByVal retrieveLaterThan As Date, ByVal retrieveLaterThanSpecified As Boolean, ByVal userState As Object)
            If (Me.GetOpenMediaRequestsByTimeOperationCompleted Is Nothing) Then
                Me.GetOpenMediaRequestsByTimeOperationCompleted = AddressOf Me.OnGetOpenMediaRequestsByTimeOperationCompleted
            End If
            Me.InvokeAsync("GetOpenMediaRequestsByTime", New Object() {retrieveLaterThan, retrieveLaterThanSpecified}, Me.GetOpenMediaRequestsByTimeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetOpenMediaRequestsByTimeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetOpenMediaRequestsByTimeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetOpenMediaRequestsByTimeCompleted(Me, New GetOpenMediaRequestsByTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/GetAllOpenMediaRequestStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllOpenMediaRequestStatus() As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> GetOpenMediaResponse
            Dim results() As Object = Me.Invoke("GetAllOpenMediaRequestStatus", New Object(-1) {})
            Return CType(results(0),GetOpenMediaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAllOpenMediaRequestStatusAsync()
            Me.GetAllOpenMediaRequestStatusAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAllOpenMediaRequestStatusAsync(ByVal userState As Object)
            If (Me.GetAllOpenMediaRequestStatusOperationCompleted Is Nothing) Then
                Me.GetAllOpenMediaRequestStatusOperationCompleted = AddressOf Me.OnGetAllOpenMediaRequestStatusOperationCompleted
            End If
            Me.InvokeAsync("GetAllOpenMediaRequestStatus", New Object(-1) {}, Me.GetAllOpenMediaRequestStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAllOpenMediaRequestStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAllOpenMediaRequestStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAllOpenMediaRequestStatusCompleted(Me, New GetAllOpenMediaRequestStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/GetServiceGroupStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetServiceGroupStatus(ByVal serviceGroupID As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal serviceGroupIDSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ServiceGroupStatus
            Dim results() As Object = Me.Invoke("GetServiceGroupStatus", New Object() {serviceGroupID, serviceGroupIDSpecified})
            Return CType(results(0),ServiceGroupStatus)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetServiceGroupStatusAsync(ByVal serviceGroupID As Integer, ByVal serviceGroupIDSpecified As Boolean)
            Me.GetServiceGroupStatusAsync(serviceGroupID, serviceGroupIDSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetServiceGroupStatusAsync(ByVal serviceGroupID As Integer, ByVal serviceGroupIDSpecified As Boolean, ByVal userState As Object)
            If (Me.GetServiceGroupStatusOperationCompleted Is Nothing) Then
                Me.GetServiceGroupStatusOperationCompleted = AddressOf Me.OnGetServiceGroupStatusOperationCompleted
            End If
            Me.InvokeAsync("GetServiceGroupStatus", New Object() {serviceGroupID, serviceGroupIDSpecified}, Me.GetServiceGroupStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetServiceGroupStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetServiceGroupStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetServiceGroupStatusCompleted(Me, New GetServiceGroupStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/GetAllOpenMediaServiceGroupStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllOpenMediaServiceGroupStatus(ByVal tenantID As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tenantIDSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> GetAllServiceGroupStatusResponse
            Dim results() As Object = Me.Invoke("GetAllOpenMediaServiceGroupStatus", New Object() {tenantID, tenantIDSpecified})
            Return CType(results(0),GetAllServiceGroupStatusResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAllOpenMediaServiceGroupStatusAsync(ByVal tenantID As Integer, ByVal tenantIDSpecified As Boolean)
            Me.GetAllOpenMediaServiceGroupStatusAsync(tenantID, tenantIDSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAllOpenMediaServiceGroupStatusAsync(ByVal tenantID As Integer, ByVal tenantIDSpecified As Boolean, ByVal userState As Object)
            If (Me.GetAllOpenMediaServiceGroupStatusOperationCompleted Is Nothing) Then
                Me.GetAllOpenMediaServiceGroupStatusOperationCompleted = AddressOf Me.OnGetAllOpenMediaServiceGroupStatusOperationCompleted
            End If
            Me.InvokeAsync("GetAllOpenMediaServiceGroupStatus", New Object() {tenantID, tenantIDSpecified}, Me.GetAllOpenMediaServiceGroupStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAllOpenMediaServiceGroupStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAllOpenMediaServiceGroupStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAllOpenMediaServiceGroupStatusCompleted(Me, New GetAllOpenMediaServiceGroupStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/SetOptions", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SetOptions(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As SetOptionsRequest, ByRef SetOptionsResult As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef SetOptionsResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("SetOptions", New Object() {request})
            SetOptionsResult = CType(results(0),Boolean)
            SetOptionsResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetOptionsAsync(ByVal request As SetOptionsRequest)
            Me.SetOptionsAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetOptionsAsync(ByVal request As SetOptionsRequest, ByVal userState As Object)
            If (Me.SetOptionsOperationCompleted Is Nothing) Then
                Me.SetOptionsOperationCompleted = AddressOf Me.OnSetOptionsOperationCompleted
            End If
            Me.InvokeAsync("SetOptions", New Object() {request}, Me.SetOptionsOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetOptionsOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetOptionsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetOptionsCompleted(Me, New SetOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/GetOMAgentsByGroup", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOMAgentsByGroup(ByVal serviceGroupID As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal serviceGroupIDSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> GetOMAgentsByGroupResponse
            Dim results() As Object = Me.Invoke("GetOMAgentsByGroup", New Object() {serviceGroupID, serviceGroupIDSpecified})
            Return CType(results(0),GetOMAgentsByGroupResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetOMAgentsByGroupAsync(ByVal serviceGroupID As Integer, ByVal serviceGroupIDSpecified As Boolean)
            Me.GetOMAgentsByGroupAsync(serviceGroupID, serviceGroupIDSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetOMAgentsByGroupAsync(ByVal serviceGroupID As Integer, ByVal serviceGroupIDSpecified As Boolean, ByVal userState As Object)
            If (Me.GetOMAgentsByGroupOperationCompleted Is Nothing) Then
                Me.GetOMAgentsByGroupOperationCompleted = AddressOf Me.OnGetOMAgentsByGroupOperationCompleted
            End If
            Me.InvokeAsync("GetOMAgentsByGroup", New Object() {serviceGroupID, serviceGroupIDSpecified}, Me.GetOMAgentsByGroupOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetOMAgentsByGroupOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetOMAgentsByGroupCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetOMAgentsByGroupCompleted(Me, New GetOMAgentsByGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/DivertRequest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DivertRequest(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As DivertOpenMediaRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> DivertOpenMediaResponse
            Dim results() As Object = Me.Invoke("DivertRequest", New Object() {request})
            Return CType(results(0),DivertOpenMediaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DivertRequestAsync(ByVal request As DivertOpenMediaRequest)
            Me.DivertRequestAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DivertRequestAsync(ByVal request As DivertOpenMediaRequest, ByVal userState As Object)
            If (Me.DivertRequestOperationCompleted Is Nothing) Then
                Me.DivertRequestOperationCompleted = AddressOf Me.OnDivertRequestOperationCompleted
            End If
            Me.InvokeAsync("DivertRequest", New Object() {request}, Me.DivertRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnDivertRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.DivertRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DivertRequestCompleted(Me, New DivertRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOpenMediaService/ModifyRequest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub ModifyRequest(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As ModifyOpenMediaRequest, ByRef ModifyRequestResult As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef ModifyRequestResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("ModifyRequest", New Object() {request})
            ModifyRequestResult = CType(results(0),Boolean)
            ModifyRequestResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ModifyRequestAsync(ByVal request As ModifyOpenMediaRequest)
            Me.ModifyRequestAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ModifyRequestAsync(ByVal request As ModifyOpenMediaRequest, ByVal userState As Object)
            If (Me.ModifyRequestOperationCompleted Is Nothing) Then
                Me.ModifyRequestOperationCompleted = AddressOf Me.OnModifyRequestOperationCompleted
            End If
            Me.InvokeAsync("ModifyRequest", New Object() {request}, Me.ModifyRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnModifyRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.ModifyRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ModifyRequestCompleted(Me, New ModifyRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class AddOpenMediaRequest
        
        Private forceToPreferredAgentField As Boolean
        
        Private forceToPreferredAgentFieldSpecified As Boolean
        
        Private iVRInfoField() As IVRInformation
        
        Private preferredAgentIDField As Integer
        
        Private preferredAgentIDFieldSpecified As Boolean
        
        Private preferredAgentLogonIDField As String
        
        Private privateDataField As String
        
        Private queueStartTimeField As System.Nullable(Of Date)
        
        Private queueStartTimeFieldSpecified As Boolean
        
        Private serviceGroupIDField As Integer
        
        Private serviceGroupIDFieldSpecified As Boolean
        
        Private serviceGroupNameField As String
        
        Private sessionPriorityField As Integer
        
        Private sessionPriorityFieldSpecified As Boolean
        
        Private tenantIDField As Integer
        
        Private tenantIDFieldSpecified As Boolean
        
        Private typeOfSessionField As Integer
        
        Private typeOfSessionFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property ForceToPreferredAgent() As Boolean
            Get
                Return Me.forceToPreferredAgentField
            End Get
            Set
                Me.forceToPreferredAgentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ForceToPreferredAgentSpecified() As Boolean
            Get
                Return Me.forceToPreferredAgentFieldSpecified
            End Get
            Set
                Me.forceToPreferredAgentFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property IVRInfo() As IVRInformation()
            Get
                Return Me.iVRInfoField
            End Get
            Set
                Me.iVRInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PreferredAgentID() As Integer
            Get
                Return Me.preferredAgentIDField
            End Get
            Set
                Me.preferredAgentIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PreferredAgentIDSpecified() As Boolean
            Get
                Return Me.preferredAgentIDFieldSpecified
            End Get
            Set
                Me.preferredAgentIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PreferredAgentLogonID() As String
            Get
                Return Me.preferredAgentLogonIDField
            End Get
            Set
                Me.preferredAgentLogonIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PrivateData() As String
            Get
                Return Me.privateDataField
            End Get
            Set
                Me.privateDataField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property QueueStartTime() As System.Nullable(Of Date)
            Get
                Return Me.queueStartTimeField
            End Get
            Set
                Me.queueStartTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QueueStartTimeSpecified() As Boolean
            Get
                Return Me.queueStartTimeFieldSpecified
            End Get
            Set
                Me.queueStartTimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceGroupID() As Integer
            Get
                Return Me.serviceGroupIDField
            End Get
            Set
                Me.serviceGroupIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ServiceGroupIDSpecified() As Boolean
            Get
                Return Me.serviceGroupIDFieldSpecified
            End Get
            Set
                Me.serviceGroupIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ServiceGroupName() As String
            Get
                Return Me.serviceGroupNameField
            End Get
            Set
                Me.serviceGroupNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SessionPriority() As Integer
            Get
                Return Me.sessionPriorityField
            End Get
            Set
                Me.sessionPriorityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SessionPrioritySpecified() As Boolean
            Get
                Return Me.sessionPriorityFieldSpecified
            End Get
            Set
                Me.sessionPriorityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TenantID() As Integer
            Get
                Return Me.tenantIDField
            End Get
            Set
                Me.tenantIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TenantIDSpecified() As Boolean
            Get
                Return Me.tenantIDFieldSpecified
            End Get
            Set
                Me.tenantIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TypeOfSession() As Integer
            Get
                Return Me.typeOfSessionField
            End Get
            Set
                Me.typeOfSessionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TypeOfSessionSpecified() As Boolean
            Get
                Return Me.typeOfSessionFieldSpecified
            End Get
            Set
                Me.typeOfSessionFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class IVRInformation
        
        Private dataField As String
        
        Private labelField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Data() As String
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Label() As String
            Get
                Return Me.labelField
            End Get
            Set
                Me.labelField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class ModifyOpenMediaRequest
        
        Private iVRInfoField() As IVRInformation
        
        Private openMediaIDField As Integer
        
        Private openMediaIDFieldSpecified As Boolean
        
        Private privateDataField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property IVRInfo() As IVRInformation()
            Get
                Return Me.iVRInfoField
            End Get
            Set
                Me.iVRInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenMediaID() As Integer
            Get
                Return Me.openMediaIDField
            End Get
            Set
                Me.openMediaIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OpenMediaIDSpecified() As Boolean
            Get
                Return Me.openMediaIDFieldSpecified
            End Get
            Set
                Me.openMediaIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PrivateData() As String
            Get
                Return Me.privateDataField
            End Get
            Set
                Me.privateDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class DivertOpenMediaResponse
        
        Private openMediaIDField As Integer
        
        Private openMediaIDFieldSpecified As Boolean
        
        Private requestStatusField As OpenMediaRequestStatus
        
        Private requestStatusFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property OpenMediaID() As Integer
            Get
                Return Me.openMediaIDField
            End Get
            Set
                Me.openMediaIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OpenMediaIDSpecified() As Boolean
            Get
                Return Me.openMediaIDFieldSpecified
            End Get
            Set
                Me.openMediaIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestStatus() As OpenMediaRequestStatus
            Get
                Return Me.requestStatusField
            End Get
            Set
                Me.requestStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RequestStatusSpecified() As Boolean
            Get
                Return Me.requestStatusFieldSpecified
            End Get
            Set
                Me.requestStatusFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Public Enum OpenMediaRequestStatus
        
        '''<remarks/>
        Success
        
        '''<remarks/>
        GroupClosed
        
        '''<remarks/>
        InvalidGroup
        
        '''<remarks/>
        TenantDisabled
        
        '''<remarks/>
        AgentLoggedOff
        
        '''<remarks/>
        InvalidID
        
        '''<remarks/>
        [Error]
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class DivertOpenMediaRequest
        
        Private openMediaIDField As Integer
        
        Private openMediaIDFieldSpecified As Boolean
        
        Private serviceGroupIDField As Integer
        
        Private serviceGroupIDFieldSpecified As Boolean
        
        Private serviceGroupNameField As String
        
        Private tenantIDField As Integer
        
        Private tenantIDFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property OpenMediaID() As Integer
            Get
                Return Me.openMediaIDField
            End Get
            Set
                Me.openMediaIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OpenMediaIDSpecified() As Boolean
            Get
                Return Me.openMediaIDFieldSpecified
            End Get
            Set
                Me.openMediaIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceGroupID() As Integer
            Get
                Return Me.serviceGroupIDField
            End Get
            Set
                Me.serviceGroupIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ServiceGroupIDSpecified() As Boolean
            Get
                Return Me.serviceGroupIDFieldSpecified
            End Get
            Set
                Me.serviceGroupIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ServiceGroupName() As String
            Get
                Return Me.serviceGroupNameField
            End Get
            Set
                Me.serviceGroupNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TenantID() As Integer
            Get
                Return Me.tenantIDField
            End Get
            Set
                Me.tenantIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TenantIDSpecified() As Boolean
            Get
                Return Me.tenantIDFieldSpecified
            End Get
            Set
                Me.tenantIDFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class GetOMAgentsByGroupResponse
        
        Private agentListField() As Integer
        
        Private serviceGroupIDField As Integer
        
        Private serviceGroupIDFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable:=false)>  _
        Public Property AgentList() As Integer()
            Get
                Return Me.agentListField
            End Get
            Set
                Me.agentListField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceGroupID() As Integer
            Get
                Return Me.serviceGroupIDField
            End Get
            Set
                Me.serviceGroupIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ServiceGroupIDSpecified() As Boolean
            Get
                Return Me.serviceGroupIDFieldSpecified
            End Get
            Set
                Me.serviceGroupIDFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class SetOptionsRequest
        
        Private agentActionOptionsField As Integer
        
        Private agentActionOptionsFieldSpecified As Boolean
        
        Private allowDifferentTypesField As Integer
        
        Private allowDifferentTypesFieldSpecified As Boolean
        
        Private closeTabOptionsField As Integer
        
        Private closeTabOptionsFieldSpecified As Boolean
        
        Private maxNumberOfSessionsField As Integer
        
        Private maxNumberOfSessionsFieldSpecified As Boolean
        
        Private resetAllOptionsField As Boolean
        
        Private resetAllOptionsFieldSpecified As Boolean
        
        Private sessionLinkOptionsField As Integer
        
        Private sessionLinkOptionsFieldSpecified As Boolean
        
        Private typeOfSessionField As Integer
        
        Private typeOfSessionFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property AgentActionOptions() As Integer
            Get
                Return Me.agentActionOptionsField
            End Get
            Set
                Me.agentActionOptionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AgentActionOptionsSpecified() As Boolean
            Get
                Return Me.agentActionOptionsFieldSpecified
            End Get
            Set
                Me.agentActionOptionsFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllowDifferentTypes() As Integer
            Get
                Return Me.allowDifferentTypesField
            End Get
            Set
                Me.allowDifferentTypesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AllowDifferentTypesSpecified() As Boolean
            Get
                Return Me.allowDifferentTypesFieldSpecified
            End Get
            Set
                Me.allowDifferentTypesFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CloseTabOptions() As Integer
            Get
                Return Me.closeTabOptionsField
            End Get
            Set
                Me.closeTabOptionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CloseTabOptionsSpecified() As Boolean
            Get
                Return Me.closeTabOptionsFieldSpecified
            End Get
            Set
                Me.closeTabOptionsFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MaxNumberOfSessions() As Integer
            Get
                Return Me.maxNumberOfSessionsField
            End Get
            Set
                Me.maxNumberOfSessionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MaxNumberOfSessionsSpecified() As Boolean
            Get
                Return Me.maxNumberOfSessionsFieldSpecified
            End Get
            Set
                Me.maxNumberOfSessionsFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResetAllOptions() As Boolean
            Get
                Return Me.resetAllOptionsField
            End Get
            Set
                Me.resetAllOptionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ResetAllOptionsSpecified() As Boolean
            Get
                Return Me.resetAllOptionsFieldSpecified
            End Get
            Set
                Me.resetAllOptionsFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SessionLinkOptions() As Integer
            Get
                Return Me.sessionLinkOptionsField
            End Get
            Set
                Me.sessionLinkOptionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SessionLinkOptionsSpecified() As Boolean
            Get
                Return Me.sessionLinkOptionsFieldSpecified
            End Get
            Set
                Me.sessionLinkOptionsFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TypeOfSession() As Integer
            Get
                Return Me.typeOfSessionField
            End Get
            Set
                Me.typeOfSessionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TypeOfSessionSpecified() As Boolean
            Get
                Return Me.typeOfSessionFieldSpecified
            End Get
            Set
                Me.typeOfSessionFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class GetAllServiceGroupStatusResponse
        
        Private statusField() As ServiceGroupStatus
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property Status() As ServiceGroupStatus()
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class ServiceGroupStatus
        
        Private openField As Boolean
        
        Private openFieldSpecified As Boolean
        
        Private serviceGroupIDField As Integer
        
        Private serviceGroupIDFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Open() As Boolean
            Get
                Return Me.openField
            End Get
            Set
                Me.openField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OpenSpecified() As Boolean
            Get
                Return Me.openFieldSpecified
            End Get
            Set
                Me.openFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceGroupID() As Integer
            Get
                Return Me.serviceGroupIDField
            End Get
            Set
                Me.serviceGroupIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ServiceGroupIDSpecified() As Boolean
            Get
                Return Me.serviceGroupIDFieldSpecified
            End Get
            Set
                Me.serviceGroupIDFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class OpenMediaRequest
        
        Private agentIDField As Integer
        
        Private agentIDFieldSpecified As Boolean
        
        Private idField As Integer
        
        Private idFieldSpecified As Boolean
        
        Private logonIDField As String
        
        Private queuePositionField As Integer
        
        Private queuePositionFieldSpecified As Boolean
        
        Private serviceGroupIDField As Integer
        
        Private serviceGroupIDFieldSpecified As Boolean
        
        Private statusField As OpenMediaStatus
        
        Private statusFieldSpecified As Boolean
        
        Private tenantIDField As Integer
        
        Private tenantIDFieldSpecified As Boolean
        
        Private timeStampField As Date
        
        Private timeStampFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property AgentID() As Integer
            Get
                Return Me.agentIDField
            End Get
            Set
                Me.agentIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AgentIDSpecified() As Boolean
            Get
                Return Me.agentIDFieldSpecified
            End Get
            Set
                Me.agentIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IDSpecified() As Boolean
            Get
                Return Me.idFieldSpecified
            End Get
            Set
                Me.idFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LogonID() As String
            Get
                Return Me.logonIDField
            End Get
            Set
                Me.logonIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QueuePosition() As Integer
            Get
                Return Me.queuePositionField
            End Get
            Set
                Me.queuePositionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QueuePositionSpecified() As Boolean
            Get
                Return Me.queuePositionFieldSpecified
            End Get
            Set
                Me.queuePositionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceGroupID() As Integer
            Get
                Return Me.serviceGroupIDField
            End Get
            Set
                Me.serviceGroupIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ServiceGroupIDSpecified() As Boolean
            Get
                Return Me.serviceGroupIDFieldSpecified
            End Get
            Set
                Me.serviceGroupIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As OpenMediaStatus
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StatusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TenantID() As Integer
            Get
                Return Me.tenantIDField
            End Get
            Set
                Me.tenantIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TenantIDSpecified() As Boolean
            Get
                Return Me.tenantIDFieldSpecified
            End Get
            Set
                Me.tenantIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TimeStamp() As Date
            Get
                Return Me.timeStampField
            End Get
            Set
                Me.timeStampField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TimeStampSpecified() As Boolean
            Get
                Return Me.timeStampFieldSpecified
            End Get
            Set
                Me.timeStampFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Public Enum OpenMediaStatus
        
        '''<remarks/>
        Unknown
        
        '''<remarks/>
        Queued
        
        '''<remarks/>
        AllocatedToAgent
        
        '''<remarks/>
        AgentProcessing
        
        '''<remarks/>
        Complete
        
        '''<remarks/>
        Failed
        
        '''<remarks/>
        Cancelled
        
        '''<remarks/>
        Clerical
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class GetOpenMediaResponse
        
        Private openMediaRequestsField() As OpenMediaRequest
        
        Private timeStampField As Date
        
        Private timeStampFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property OpenMediaRequests() As OpenMediaRequest()
            Get
                Return Me.openMediaRequestsField
            End Get
            Set
                Me.openMediaRequestsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TimeStamp() As Date
            Get
                Return Me.timeStampField
            End Get
            Set
                Me.timeStampField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TimeStampSpecified() As Boolean
            Get
                Return Me.timeStampFieldSpecified
            End Get
            Set
                Me.timeStampFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class CancelOpenMediaRequest
        
        Private cancelIfAllocatedField As Boolean
        
        Private cancelIfAllocatedFieldSpecified As Boolean
        
        Private doNotReportField As Boolean
        
        Private doNotReportFieldSpecified As Boolean
        
        Private openMediaIDField As Integer
        
        Private openMediaIDFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property CancelIfAllocated() As Boolean
            Get
                Return Me.cancelIfAllocatedField
            End Get
            Set
                Me.cancelIfAllocatedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CancelIfAllocatedSpecified() As Boolean
            Get
                Return Me.cancelIfAllocatedFieldSpecified
            End Get
            Set
                Me.cancelIfAllocatedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DoNotReport() As Boolean
            Get
                Return Me.doNotReportField
            End Get
            Set
                Me.doNotReportField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DoNotReportSpecified() As Boolean
            Get
                Return Me.doNotReportFieldSpecified
            End Get
            Set
                Me.doNotReportFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenMediaID() As Integer
            Get
                Return Me.openMediaIDField
            End Get
            Set
                Me.openMediaIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OpenMediaIDSpecified() As Boolean
            Get
                Return Me.openMediaIDFieldSpecified
            End Get
            Set
                Me.openMediaIDFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Solidus.OpenMedia.Contracts.DataContracts"& _ 
        "")>  _
    Partial Public Class AddOpenMediaResponse
        
        Private eWTField As Integer
        
        Private eWTFieldSpecified As Boolean
        
        Private openMediaIDField As Integer
        
        Private openMediaIDFieldSpecified As Boolean
        
        Private queuePositionField As Integer
        
        Private queuePositionFieldSpecified As Boolean
        
        Private requestStatusField As OpenMediaRequestStatus
        
        Private requestStatusFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property EWT() As Integer
            Get
                Return Me.eWTField
            End Get
            Set
                Me.eWTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property EWTSpecified() As Boolean
            Get
                Return Me.eWTFieldSpecified
            End Get
            Set
                Me.eWTFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenMediaID() As Integer
            Get
                Return Me.openMediaIDField
            End Get
            Set
                Me.openMediaIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OpenMediaIDSpecified() As Boolean
            Get
                Return Me.openMediaIDFieldSpecified
            End Get
            Set
                Me.openMediaIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QueuePosition() As Integer
            Get
                Return Me.queuePositionField
            End Get
            Set
                Me.queuePositionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QueuePositionSpecified() As Boolean
            Get
                Return Me.queuePositionFieldSpecified
            End Get
            Set
                Me.queuePositionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestStatus() As OpenMediaRequestStatus
            Get
                Return Me.requestStatusField
            End Get
            Set
                Me.requestStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RequestStatusSpecified() As Boolean
            Get
                Return Me.requestStatusFieldSpecified
            End Get
            Set
                Me.requestStatusFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub AddRequestCompletedEventHandler(ByVal sender As Object, ByVal e As AddRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AddOpenMediaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AddOpenMediaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub CancelRequestCompletedEventHandler(ByVal sender As Object, ByVal e As CancelRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property CancelRequestResult() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property CancelRequestResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetOpenMediaRequestStatusByIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetOpenMediaRequestStatusByIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetOpenMediaRequestStatusByIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetOpenMediaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetOpenMediaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetOpenMediaRequestHistoryByIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetOpenMediaRequestHistoryByIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetOpenMediaRequestHistoryByIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetOpenMediaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetOpenMediaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetOpenMediaRequestsByTimeCompletedEventHandler(ByVal sender As Object, ByVal e As GetOpenMediaRequestsByTimeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetOpenMediaRequestsByTimeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetOpenMediaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetOpenMediaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetAllOpenMediaRequestStatusCompletedEventHandler(ByVal sender As Object, ByVal e As GetAllOpenMediaRequestStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAllOpenMediaRequestStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetOpenMediaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetOpenMediaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetServiceGroupStatusCompletedEventHandler(ByVal sender As Object, ByVal e As GetServiceGroupStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetServiceGroupStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ServiceGroupStatus
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ServiceGroupStatus)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetAllOpenMediaServiceGroupStatusCompletedEventHandler(ByVal sender As Object, ByVal e As GetAllOpenMediaServiceGroupStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAllOpenMediaServiceGroupStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetAllServiceGroupStatusResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetAllServiceGroupStatusResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub SetOptionsCompletedEventHandler(ByVal sender As Object, ByVal e As SetOptionsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetOptionsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property SetOptionsResult() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property SetOptionsResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetOMAgentsByGroupCompletedEventHandler(ByVal sender As Object, ByVal e As GetOMAgentsByGroupCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetOMAgentsByGroupCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetOMAgentsByGroupResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetOMAgentsByGroupResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub DivertRequestCompletedEventHandler(ByVal sender As Object, ByVal e As DivertRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DivertRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DivertOpenMediaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DivertOpenMediaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ModifyRequestCompletedEventHandler(ByVal sender As Object, ByVal e As ModifyRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ModifyRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property ModifyRequestResult() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ModifyRequestResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
End Namespace
